######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 29 17:17:53 2011
######################################################################

TEMPLATE = app
TARGET = mrxt
OBJECTS_DIR = ./objects
DEPENDPATH += . \
              src \
              include/model \
              include/mylib \
              src/model \
              src/mylib \
              include/architecture/basics \
              include/architecture/planner \
              include/architecture/reactive \
              include/architecture/slam \
              include/model/sensors \
              src/architecture/basics \
              src/architecture/planner \
              src/architecture/reactive \
              src/architecture/slam \
              src/model/sensors \
              include/architecture/planner/auxiliar \
              include/architecture/slam/mapbuilders \
              include/architecture/slam/mapdata \
              src/architecture/planner/auxiliar \
              src/architecture/slam/mapbuilders \
              src/architecture/slam/mapdata
INCLUDEPATH += . \
	       include \
               include/architecture/basics \
               include/architecture/slam \
               include/architecture/slam/mapdata \
               include/mylib \
               include/model/sensors \
               include/model \
	       include/ui \
               include/architecture/reactive \
               include/architecture/planner \
               include/architecture/planner/auxiliar \
               include/architecture/slam/mapbuilders \
	    
	       
LIBS += -lpthread -lm -lopencv_core -lopencv_highgui  -lloki

# Input
HEADERS += include/model/robotBase.h \
           include/model/simulatedModel.h \
           include/model/worldModelInterface.h \
           include/mylib/ClMutex.h \
           include/mylib/ClThread.h \
           include/mylib/ComThread.h \
           include/mylib/ConfigFile.h \
           include/mylib/matFuns.h \
           include/mylib/robotTypes.h \
           include/mylib/stepEvent.h \
           include/mylib/StringTokenizer.h \
           include/architecture/basics/explorer.h \
           include/architecture/basics/robot.h \
           include/architecture/basics/team.h \
           include/architecture/planner/CoordinatedPlanner.h \
           include/architecture/planner/FrontierGreedyPlanner.h \
           include/architecture/planner/FSAPlanner.h \
           include/architecture/planner/HybridPlanner.h \
           include/architecture/planner/IGPlanner.h \
           include/architecture/planner/IntegratedIGPlanner.h \
           include/architecture/planner/MarketPlanner.h \
           include/architecture/planner/planner.h \
           include/architecture/reactive/localPotentialField.h \
           include/architecture/reactive/reactive.h \
           include/architecture/reactive/reactiveGauss.h \
           include/architecture/slam/slamInterface.h \
           include/model/sensors/landmarksData.h \
           include/model/sensors/rangeSensorData.h \
           include/architecture/planner/auxiliar/pathPlanning.h \
           include/architecture/planner/auxiliar/treeNode.h \
           include/architecture/slam/mapbuilders/EKFilter.h \
           include/architecture/slam/mapbuilders/particle.h \
           include/architecture/slam/mapbuilders/RBPFilter.h \
           include/architecture/slam/mapbuilders/vslamFilter.h \
           include/architecture/slam/mapdata/binMap.h \
           include/architecture/slam/mapdata/gridMapInterface.h \
           include/architecture/slam/mapdata/occupancyGridMap.h \
           include/architecture/slam/mapdata/OGMReflectProb.h \
           include/architecture/slam/mapdata/visualMap.h \
           include/architecture/slam/mapdata/vMapArray.h \
	   include/ui/mainwindow.h

SOURCES += src/mrxt.cpp \
           src/model/robotBase.cpp \
           src/model/simulatedModel.cpp \
           src/mylib/ClMutex.cpp \
           src/mylib/ClThread.cpp \
           src/mylib/ComThread.cpp \
           src/mylib/ConfigFile.cpp \
           src/mylib/matFuns.cpp \
           src/mylib/stepEvent.cpp \
           src/mylib/StringTokenizer.cpp \
           src/architecture/basics/explorer.cpp \
           src/architecture/basics/robot.cpp \
           src/architecture/basics/team.cpp \
           src/architecture/planner/CoordinatedPlanner.cpp \
           src/architecture/planner/FrontierGreedyPlanner.cpp \
           src/architecture/planner/FSAPlanner.cpp \
           src/architecture/planner/HybridPlanner.cpp \
           src/architecture/planner/IGPlanner.cpp \
           src/architecture/planner/IntegratedIGPlanner.cpp \
           src/architecture/planner/MarketPlanner.cpp \
           src/architecture/planner/planner.cpp \
           src/architecture/reactive/localPotentialField.cpp \
           src/architecture/reactive/reactive.cpp \
           src/architecture/reactive/reactiveGauss.cpp \
           src/model/sensors/landmarksData.cpp \
           src/model/sensors/rangeSensorData.cpp \
           src/architecture/planner/auxiliar/pathPlanning.cpp \
           src/architecture/planner/auxiliar/treeNode.cpp \
           src/architecture/slam/mapbuilders/EKFilter.cpp \
           src/architecture/slam/mapbuilders/particle.cpp \
           src/architecture/slam/mapbuilders/RBPFilter.cpp \
           src/architecture/slam/mapbuilders/vslamFilter.cpp \
           src/architecture/slam/mapdata/binMap.cpp \
           src/architecture/slam/mapdata/occupancyGridMap.cpp \
           src/architecture/slam/mapdata/OGMReflectProb.cpp \
           src/architecture/slam/mapdata/visualMap.cpp \
           src/architecture/slam/mapdata/vMapArray.cpp \
	   src/ui/mainwindow.cpp

FORMS     = ui/mainWindow.ui \
	    ui/RobotSettingsDialog.ui \
	    ui/scenePropertiesDialog.ui \
	    ui/slamOptionsDialog.ui \
	    ui/strategyOptionsDialog.ui \
	    ui/about.ui \
	    ui/appConfigDialog.ui

unix {
  #VARIABLES
  isEmpty(PREFIX) {
    PREFIX = /usr
  }
  BINDIR = $$PREFIX/bin
  DATADIR =$$PREFIX/share

  DEFINES += DATADIR=\\\"$$DATADIR\\\" PKGDATADIR=\\\"$$PKGDATADIR\\\"

  #MAKE INSTALL

  INSTALLS += target maps configfiles

  target.path =$$BINDIR

  maps.path = $$DATADIR/mrxt/maps
  maps.files += maps/scene1.jpg
  maps.files += maps/scene2.jpg
  maps.files += maps/scene1.map
  maps.files += maps/scene2.map
  maps.files += maps/scene1.omap
  maps.files += maps/scene2.omap

  configfiles.path = $$DATADIR/mrxt/config
  configfiles.files += config/app.config
  configfiles.files += config/slam.config
  configfiles.files += config/tec0.config
  configfiles.files += config/tec1.config
  configfiles.files += config/tec2.config
  configfiles.files += config/tec3.config
  configfiles.files += config/tec4.config
  configfiles.files += config/tec5.config
  configfiles.files += config/tec6.config

}



